version: '3'
services:
  billing-service:
    build:
      context: ./billing-service
      dockerfile: Dockerfile
    ports:
      - 5006:5006
  inventory-service:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    ports:
      - 5001:5001
  shipping-service:
    build:
      context: ./shipping-service
      dockerfile: Dockerfile
    ports:
      - 5009:5009
  users-service:
    build:
      context: ./users-service
      dockerfile: Dockerfile
    ports:
      - 5003:5003

  webhook-service:
    build:
      context: ./webhook-service
      dockerfile: Dockerfile
    ports:
      - 5007:5007

  data-service:
    build:
      context: ./data-service
      dockerfile: Dockerfile
    ports:
      - 5008:5008

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5673:5672
        - 15673:15672
