apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: 19369-redis-pod
  template:
    metadata:
      labels:
        name: 19369-redis-pod
    spec:
      containers:
      - name: 19369-redis-pod
        image: redis:latest
        