# kubectl run nginx --image=nginx
# kubectl describe pod newpods-<id>
# kubectl run redis --image=redis123 --dry-run=client -o yaml > redis-definition.yaml

apiVersion: v1
kind: Pod
metadata:
 name: 19369-redis-pod
spec:
 containers:
  - name: 19369-redis-pod
    image: redis:latest
    ports:
      - containerPort: 1936
       